import React, { useState } from 'react';
import { TimelineEvent } from '../types';
import { generateClinicalSynopsis } from '../services/geminiService';
import { IconReport, IconActivity } from './ui/Icons';

interface ClinicalSynopsisProps {
  events: TimelineEvent[];
  patientName: string;
}

export const ClinicalSynopsis: React.FC<ClinicalSynopsisProps> = ({ events, patientName }) => {
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    const result = await generateClinicalSynopsis(patientName, events);
    setReport(result);
    setLoading(false);
  };

  return (
    <div className="h-full flex flex-col bg-slate-50 p-4 lg:p-8 overflow-y-auto">
      <div className="max-w-4xl mx-auto w-full">
        
        {/* Header Action */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
              <IconReport /> Clinical Synopsis
            </h1>
            <p className="text-slate-500 mt-1">AI-synthesized summary for healthcare providers.</p>
          </div>
          
          <button
            onClick={handleGenerate}
            disabled={loading}
            className={`px-6 py-3 rounded-lg shadow-md font-medium flex items-center gap-2 transition-all ${
              loading 
                ? 'bg-slate-300 cursor-not-allowed text-slate-500' 
                : 'bg-indigo-600 hover:bg-indigo-700 text-white'
            }`}
          >
            {loading ? (
              <>
                <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></div>
                Synthesizing...
              </>
            ) : (
              <>
                <IconActivity /> Generate New Report
              </>
            )}
          </button>
        </div>

        {/* Empty State */}
        {!report && !loading && (
          <div className="bg-white rounded-xl border border-dashed border-slate-300 p-12 text-center">
            <div className="w-16 h-16 bg-indigo-50 text-indigo-500 rounded-full flex items-center justify-center mx-auto mb-4">
              <IconReport />
            </div>
            <h3 className="text-lg font-semibold text-slate-700">Ready to Generate</h3>
            <p className="text-slate-500 max-w-md mx-auto mt-2">
              Helios will analyze {events.length} recent health events, vital signs, and family care notes to create a concise clinician summary.
            </p>
          </div>
        )}

        {/* Report View */}
        {report && (
          <div className="bg-white shadow-xl rounded-xl overflow-hidden border border-slate-200 animate-fade-in">
            <div className="bg-slate-900 text-white p-6 flex justify-between items-start">
              <div>
                <h2 className="text-xl font-bold font-serif">Helios Clinical Summary</h2>
                <p className="text-indigo-200 text-sm mt-1">Patient: {patientName} • DOB: 05/12/1954</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-400 uppercase tracking-wider">Generated</p>
                <p className="font-mono">{new Date().toLocaleDateString()}</p>
              </div>
            </div>
            
            <div className="p-8 lg:p-12 prose prose-slate max-w-none">
                {/* Rendering HTML safely since we trust Gemini's structured output based on prompt */}
                <div dangerouslySetInnerHTML={{ __html: report }} />
            </div>

            <div className="bg-amber-50 border-t border-amber-100 p-4 text-center">
              <p className="text-xs text-amber-800 font-medium">
                DISCLAIMER: This report is generated by AI based on user-reported data. It is not a medical diagnosis. 
                Please verify all critical information with the patient.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
